title: "Livan Центр Оренбург"
description: "Официальный дилерский центр Livan в Оренбурге"
keywords: ""
locale: ru_RU
logo_name: "Центр Оренбург"
phone: "8 (3532) 40-41-41"
postal_code: "460019"
address: "г. Оренбург, Загородное шоссе, 13а"
office_hours: "Понедельник-пятница: 9.00-19.00<br> Суббота: 10.00-18.00<br> Воскресенье: 10.00-17.00" 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://livanorenburg.ru" # the base hostname & protocol for your site, e.g. http://example.com
# url: ""
company: "ООО «Азимут»"
inn: 5609202193
ogrn: 1235600004232

destination: ../_site/

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

page_excerpts: true

collections:
  special_offers:
    output: true
    permalink: /special-offers/:title
  cars:
    output: true
    permalink: /cars/:name
  vacancies:
    output: true
    permalink: /vacancies/:name

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - src
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
