name: Generate Jekyll Files from XML

on:
  push:
    branches:
      - cars

jobs:
  build:
    runs-on: ubuntu-latest

    # Указываете окружение и его переменные
    environment:
      name: production
      url: ${{ env.ENV_XML_URL }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Download XML
      run: |
        curl ${{ vars.ENV_XML_URL }} -o livan.xml

    - name: Set XML_URL as environment variable
      run: echo "XML_URL=${{ vars.ENV_XML_URL }}" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10
        architecture: "x64"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Generate files
      run: python .github/scripts/update_cars.py

    - name: Check for changes
      id: check_changes
      run: |
        git diff --exit-code || echo "changes=true" >> $GITHUB_ENV
      continue-on-error: true

    - name: Commit files
      if: env.changes == 'true'
      run: |
        git config --local user.email "support+actions@github.com"
        git config --local user.name "github-actions-bot"
        git add cars/*.html
        git commit -m "Update cars from XML"
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
